Adding proxy support
paritytech/polkadot-staking-dashboard pull request #745
Opened 2023-03-11 10:12 UTC by TingALin

Addresses #413

2023-03-14 01:55 UTC, TingALin commented
Regarding the next step, thinking about one of the following functions:

- isDelegate(delegatee: MaybeAccount)->boolean
- proxiedAccounts(delegatee: MaybeAccount)-> Array<ProxyAccount>
- proxiedAccounts(delegatee: MaybeAccount)-> Array<MaybeAccount>

2023-03-14 14:17 UTC, rossbulat requested changes

2023-03-14 14:17 UTC, rossbulat commented on src/contexts/Accounts/Proxies/index.tsx
> +  const [delegators, setDelegators] = useState<Array<MaybeAccount>>([]);
Why is this `delegators`? We need to store `delegates`, and the above `proxies` state stores the delegators, no?

This should not be `MaybeAccount` as there will never be a `null` value being stored. In addition, we need to store more than the address here. We also need the "real" account, or delegator account alongside it.

2023-03-14 14:17 UTC, rossbulat commented on src/contexts/Accounts/Proxies/index.tsx
> +      let newProxies = proxiesRef.current;
this line is not being used, just do `const newProxies` on line 61.

2023-03-14 14:17 UTC, rossbulat commented on src/contexts/Accounts/Proxies/index.tsx
> +    for (const a of accounts) {
Why is `accounts` being used? This `useEffect` just needs to loop through `proxiesRef.current` and reverse the record to be `delegate -> proxies` instead.

2023-03-14 14:17 UTC, rossbulat commented on src/contexts/Accounts/Proxies/index.tsx
> +  const getProxyAccounts = (address: MaybeAccount) => {
Should this be renamed to `getDelegates`?

2023-03-21 04:35 UTC, rossbulat approved these changes

2023-03-21 04:35 UTC, merged