[WIP] Ledger transaction help icon
paritytech/polkadot-staking-dashboard pull request #837
Opened 2023-03-30 11:10 UTC by TingALin

HelpIcons next to the rejected Ledger transaction pending message that open the help overlay states

2023-04-02 10:37 UTC, rossbulat commented on src/library/SubmitTx/Wrappers.tsx
> +        font-size: 1.1rem;
```suggestion
        font-size: 1rem;
```

2023-04-02 10:38 UTC, rossbulat commented on src/library/SubmitTx/ManualSign.tsx
> +            {defaultMessage ===
There should be `helpKey` returned by determineStatusCode, and that helpKey should be tested here.

2023-04-02 10:38 UTC, rossbulat requested changes
An additional `helpKey` needs to be returned from determineStatusCode.

2023-04-03 15:14 UTC, rossbulat commented on src/library/SubmitTx/Wrappers.tsx
>          color: var(--text-color-secondary);
Move this variable to the top of this class.

2023-04-03 15:15 UTC, rossbulat commented on src/config/help.ts
>        'Ledger Hardware Wallets',
These should be removed as they have been moved under the `ledger` key.

2023-04-03 15:15 UTC, rossbulat commented on src/config/help.ts
> +      'Ledger Rejected Transaction Options',
Rename to `Ledger Rejected Transaction`.

2023-04-03 15:17 UTC, rossbulat commented on src/locale/cn/help.json
> +      "ledgerRejectedTransactionOptions": [
With the above rename this will be `ledgerRejectedTransaction`

2023-04-03 15:17 UTC, rossbulat commented on src/locale/en/help.json
> +      "ledgerRejectedTransactionOptions": [
With the above rename this will be `ledgerRejectedTransaction`.

2023-04-03 15:17 UTC, rossbulat commented on src/locale/en/help.json
> +        ["You can either sign the transaction again or close the window"]
Missing full stop, `.`.

2023-04-04 03:25 UTC, TingALin commented
> In addition to the comments, `defaultMessage` is still not `helpKey` supported. I also expect more new `helpKeys` to explain the various states of the Ledger device.

Considering defaultMessage is wherever StatusCode is , I think it's more reasonable to just have the helpKey in defaultMessage, and leave the StatusCode the way it was, but for now, both of the states support helpKey

2023-04-08 02:46 UTC, rossbulat commented
⚠️ master -> main branch migration ⚠️
Polkadot staking dashboard's master branch has been renamed to main. If developing locally, remember to update .git/config and fetch main to get the latest default branch.

2023-04-09 06:03 UTC, rossbulat commented
I just need to expand on the help content. After which @TingALin please translate into CN. Will let you know when the EN versions are pushed.

2023-04-09 07:26 UTC, rossbulat commented on src/locale/cn/help.json
> +          "The transaction was rejected on the Ledger device and will not be submitted.",
@TingALin translations needed.

2023-04-09 07:27 UTC, rossbulat reviewed
Just translations needed now.

2023-04-09 07:27 UTC, rossbulat commented on src/locale/cn/help.json
> +          "Timeout errors can occur when the Ledger device is busy, or when an operation fails to complete in time.",
@TingALin translations needed.

2023-04-09 07:27 UTC, rossbulat commented on src/locale/cn/help.json
> +      "openAppOnLedger": [
@TingALin translations needed.

2023-04-09 07:27 UTC, rossbulat commented on src/locale/cn/help.json
> +      "wrongTransaction": [
@TingALin translations needed.

2023-04-09 10:34 UTC, rossbulat approved these changes

2023-04-09 10:35 UTC, merged